version: "2"
services:
    web:
      build: "./web"
      ports:
        - "3000:3000"
    nginx:
      host: "twork"
      domainname: "twork.io"
      build: "./nginx"
      ports:
        - "80:80"
      links:
        - web:web
