version: "2"
host: twork
domainname: twork.io
services:
    web:
      build: "./web"
      ports:
        - "3000:3000"
    nginx:
      build: "./nginx"
      ports:
        - "80:80"
      links:
        - web:web
